pypi-ipyparallel: Autospec creation for update from version 8.6.1 to version 8.7.0
Benjamin Ragan-Kelley (28):
      Bump to 8.6.2.dev
      don't propagate logs in IPython
      bump mac test env
      inject control thread delay to make wait_for_send more reliable
      test docs on CI
      build docs on CI
      Fix docs linkcheck
      trade nbsphinx for myst-nb
      fallback import when using notebook and jupyter_server is unavailable
      use pytest.warns to assert warnings
      one big dependabot PR
      update labextension to jlab 4
      Bump to 8.7.0.dev
      require Python 3.8
      update pre-commit
      remove unused job_file traitlet
      switch to react18 createRoot
      update direct dependencies
      yarn doesn't need to be in devDependencies
      jlpm dlx yarn-berry-deduplicate
      improve deprecation messaging around `ipcluster nbextension`
      update micromamba bootstrap in ci/ssh Dockerfile
      log launcher output at warning-level in case of nonzero exit code
      publish via trusted publishers
      changelog for 8.7
      add ControllerLauncher.connection_info_timeout config
      one more new thing
      Bump to 8.7.0

Gonzalo Tornaría (1):
      fix utcnow deprecation

Mattias Ellert (4):
      Resolve warning during documentation generation:
      Resolve warning during documentation generation:
      Resolve warning during documentation generation:
      Fix AttributeError: 'super' object has no attribute 'teardown'

Michał Górny (1):
      Use pre-3.10 serialization code on PyPy3.10

Miro Hrončok (1):
      Fix unittest.mock usage on Python 3.12

dependabot[bot] (11):
      Bump @typescript-eslint/eslint-plugin from 5.55.0 to 5.59.2
      Bump semver from 5.7.1 to 5.7.2
      Bump word-wrap from 1.2.3 to 1.2.4
      Bump the lab group with 1 update
      Bump actions/checkout from 3 to 4
      Bump the lab group with 18 updates
      Bump postcss from 8.4.29 to 8.4.31
      Bump actions/setup-python from 4 to 5
      Bump actions/upload-artifact from 3 to 4
      Bump actions/cache from 3 to 4
      Bump codecov/codecov-action from 3 to 4

pre-commit-ci[bot] (12):
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] pre-commit autoupdate
      [pre-commit.ci] auto fixes from pre-commit.com hooks
      [pre-commit.ci] auto fixes from pre-commit.com hooks